name: GitHub Pages

on:
  push:
    branches: [master]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: npm ci
      - name: Build
        env:
          RUNTIME_ENV: non-prod
          REACT_APP_GA_TRACKING_ID: add-GA-ID-here
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RISHIKESHAVAN/marketplace.git
          npm run deploy
